version: '3'
services:
  nera-backend:
    container_name: nera-backend
    image: thaisperlho/nera-api:latest
  environment:
    PORT: 8081

  nera-frontend:
    image: thaisperlho/nera-app:latest
    container_name: nera-frontend
    environment:
      - REACT_APP_API_URL=http://nera-backend:8081
    depends_on:
      - nera-backend
    links:
      - nera-backend
    ports:
      - 8082:3000
